CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  passworld VARCHAR(255) NOT NULL
  -- email VARCHAR(255) NOT NULL UNIQUE,
  -- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DROP TABLE IF EXISTS library_db.`user`;

-- DROP DATABASE IF EXISTS library_db;